version: '2'
services:
  app_monitoring:
    build:
      context: .
      dockerfile: Kartaca.API.Monitoring/Dockerfile
    ports:
      - "5000:80"
  app_api:
    build:
      context: .
      dockerfile: Kartaca.API/Dockerfile
    ports:
      - "5003:80"